# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: maven-settings-action
      uses: s4u/maven-settings-action@v2.4.1
      with:
        mirrors: >-
          [{ "id": "mulesoft-plugin-releases-mirror", "name": "MulesoftPluginReleasesMirror", "mirrorOf": "mulesoft-plugin-releases", "url": "https://repository.mulesoft.org/releases/" },
          { "id": "mulesoft-plugin-snapshots-mirror", "name": "MulesoftPluginSnapshotsMirror", "mirrorOf": "mulesoft-plugin-snapshots", "url": "https://repository.mulesoft.org/snapshots/" }]

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
